# A project Makefile for the example VS1053 'client' code.

PROJECT_NAME := VS1053-example

SW_DIR = $(realpath ../..)
include ../../common.vars

EXTRA_COMPONENT_DIRS += $(realpath .)

include $(IDF_PATH)/make/project.mk
