# A project Makefile for a simple mp3 player.

PROJECT_NAME := simple-player

SW_DIR = $(realpath ..)
include ../common.vars

EXTRA_COMPONENT_DIRS += $(realpath .)

include $(IDF_PATH)/make/project.mk
